// <auto-generated />
using BooksRestApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksRestApi.Migrations
{
    [DbContext(typeof(BooksRestApiContext))]
    [Migration("20261006194216_book data added")]
    partial class bookdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksRestApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "James Clear",
                            Title = "Atomic Habits",
                            YearPublished = 2018
                        },
                        new
                        {
                            Id = 2,
                            Author = "Cal Newport",
                            Title = "Deep Work",
                            YearPublished = 2016
                        },
                        new
                        {
                            Id = 3,
                            Author = "Stephen R. Covey",
                            Title = "The 7 Habits of Highly Effective People",
                            YearPublished = 1989
                        },
                        new
                        {
                            Id = 4,
                            Author = "Carol S. Dweck",
                            Title = "Mindset",
                            YearPublished = 2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
